### ISSUE TITLE
Python 3 won't sort lists of dictionaries

### ISSUE THREAD

**Issue by andyclymer** [LettError/MutatorMath#103]
A few places around this line, lists of dictionaries are sorted:

https://github.com/LettError/MutatorMath/blob/0b64604665af7eb0a6e55e17947d650de91cce48/Lib/mutatorMath/objects/location.py#L652

...but Python 3 doesn't do this any more. I'm trying to figure out how important the sorting is here to the rest of the functionality, or which key it should be sorted on, so I thought I'd open an issue for now.

**Comment by andyclymer** [comment]
Ah, interesting! In that case my problem might be one step higher, there's a TypeError when using the DesignSpaceEditor extension in RoboFont:

```
.../mutatorMath/objects/location.py", line 652, in biasFromLocations
TypeError: '<' not supported between instances of 'collections.OrderedDict' and 'collections.OrderedDict'
```

...so maybe the extension isn't preparing the location objects properly. I can look further into it over there if you don't think it's a problem in MutatorMath.

**Comment by LettError** [comment]
Please consider moving to [UFOProcessor](https://github.com/LettError/ufoProcessor) for generating UFOs out of designspaces.
