### ISSUE TITLE
Issue with Location Node Parsing 

### ISSUE THREAD

**Issue by mdileep** [LettError/MutatorMath#11]
Consider the following Code Snippet  where yvalue  alone was  mentioned  then  mutatorMath is throwing exception " Invalid float() value"
~~~~xml
[..] 
<location>
                <dimension name="width" yvalue="0" />
</location>
[..]
~~~~
Where as following snippet is  working fine.
~~~~xml
[..] 
<location>
                <dimension name="width" xvalue="0" />
</location>
[..]
~~~~
Changes to be made for the following function.
~~~~python
def readLocationElement(self, locationElement):
~~~~

**Comment by LettError** [comment]
The yvalue value is only necessary for anisotropic interpolation when it is different from xvalue. It's used when a shape is interpolated with different factors for horizontal and vertical.
