### ISSUE TITLE
Output ufo is not fontforge  ready

### ISSUE THREAD

**Issue by mdileep** [LettError/MutatorMath#12]
1. Fontforge (On Windows 10&7  tested on Both) is stop working when attempting to the open the output file 
 * mutatorMath\test\ufo\data\instances\A\testOutput_glyphs.ufo

2. Fontforge opened the files but all glyphs are blank
 * mutatorMath\test\ufo\data\instances\B\testOutput_kerning.ufo 
 * mutatorMath\test\ufo\data\instances\C\testOutput_kerning_muted.ufo
 * mutatorMath\test\ufo\data\instances\D\testOutput_info.ufo

**Comment by benkiel** [comment]
@mdileep #2 on your list: those test UFOs only test kerning, kerning being muted, and font info; there are no glyph outlines in those UFOs, so they will show up blank.

For #1 does Fontforge give any error messages when trying to open, or does it just hang?

**Comment by mdileep** [comment]
Thanks
#2. I too realized that  there are no glyphs files as muted.
#1. It doesn't give any error. Just stops working. (Fontforge closes itself)
#3. I tried with other files  by modifying the parameters but the behavior is #1.

**Comment by typesupply** [comment]
This sounds like a FontForge bug. If FontForge is crashing while trying to read any UFO, the app is probably making assumptions about the incoming data. That's not a format issue, it's an app issue. Besides, these UFOs are files for unit testing. They aren't examples of full output.

**Comment by mdileep** [comment]
@typesupply  Thanks.Got your points. I have another  question not related to this issue.  To use the MM we need atleast 2 fonts with similar design. But how to create the second font file based om  1st font file?
It's a follow-up question of https://github.com/LettError/MutatorMath/issues/6

**Comment by LettError** [comment]
You need to draw and design that other master. There is no magic. Once two extreme versions exist you can interpolate them.
