### ISSUE TITLE
Not interpolating glyphs without Unicode value

### ISSUE THREAD

**Issue by mdileep** [LettError/MutatorMath#13]
Languages like Telugu/ Devanagari  (Indic family)  will have many glyphs without unicode value assigned directly. Such glyphs are not being interpolated. Is that a expected behavior? or needs to make any changes to either UFO or design space.  Note that These glyphs uses GSUB/GPOS rules for rendering.

**Comment by benkiel** [comment]
Glyph names between the two fonts need to be the same, and the glyphs need to be compatible (same number of points, same number of contours, same order of contours) to interpolate. I would make sure your glyphs are compatible for interpolation, it sounds like they may not be. I would try running DesignSpaceDocumentWriter with verbose set to True to get more feedback.
