### ISSUE TITLE
Diagram drawbot scripts?

### ISSUE THREAD

**Issue by davelab6** [LettError/MutatorMath#24]
fe3b12a4f10518e9aa8bbee30234f4f2e6a27621 adds JPGs and f0d3078332a307de83c6cdeb0d937fcf19b90f2c explains 

> These graphs were made with Drawbot

I wonder if you'd like to publish the drawbot sources? :)

**Comment by LettError** [comment]
I would definitely like to publish the Drawbot source. It depends on a new argument to the getFactors method, which is now part of this repository, but has not yet found its way to DrawBot. When DB can run it I will post it here.

**Comment by davelab6** [comment]
Awesome, thanks you! Great work on the documentation btw, really good stuff :D

**Comment by typemytype** [comment]
FYI: DrawBot 3.78 has the current MutatorMath (1.8)

**Comment by LettError** [comment]
Thanks @typemytype! [Drawbot script](https://github.com/LettError/MutatorMath/blob/master/Docs/mutatorMath_pyramids_and_wedges.py) added. Have fun @davelab6

**Comment by davelab6** [comment]
Awesome! Thanks!! :D
