### ISSUE TITLE
Anisotropic interpolation produces wrong (-90°) Italic angle for instances

### ISSUE THREAD

**Issue by frankrolf** [LettError/MutatorMath#259]
First pointed out by @kaibernau:

An anisotropic interpolation will result in an unexpected Italic angle for the instance UFOs.
Anisotropic interpolation basically splits the x- and y- axis by allowing different factors for each.
This is how to indicate it for a given instance:
```
        <dimension name="weight" xvalue="57" yvalue="52"/>

```
In the attached project, the Italic angle for both masters is -11°.
Using anisotropic interpolation, the italic angle for the instance ends up as -90°.
This is true for any value of `y`, including `0` and `= x`

I reproduced Kai’s finding using the AFDKO’s `makeinstancesufo`:

```
makeinstancesufo -ac -d designspace.designspace
# -ac switches off autohint/checkoutlinesufo
```

[italic_angle_issue.zip](https://github.com/LettError/MutatorMath/files/6442400/italic_angle_issue.zip)

**Comment by LettError** [comment]
This would be an issue for FontMath.MathInfo. MutatorMath does not touch these values.
Following explores the values a bit - it's not an answer just yet. What do we expect of these results? 

```python
from fontMath.mathInfo import MathInfo
from fontParts.fontshell import RInfo 

def v(x, y, angle=-11):
	m = RInfo()
	m.italicAngle = angle
	mi = m.toMathInfo(guidelines=False)
	print(f'{x, y} -> {(mi*(x,y)).italicAngle}')

# expect no change
v(1,1)

# expect angle == 0
v(0,0)

# expect horizontals to increase
v(2,1)

# what to expect here? 
v(0.57, 0.52)
```
```
(1, 1) -> -11.0
(0, 0) -> -0.0
(2, 1) -> -5.551150890446086
(0.57, 0.52) -> -10.055693239309816
```

**Comment by frankrolf** [comment]
Thank you – sorry for filing in the wrong repo. I think you might be able to transfer the issue since you presumably have admin privileged for both repos? https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

Thanks also for the exploration – I think the answer could be found visually by anisotropically interpolating a typical vertical line in both masters (such as the cap height)?

**Comment by LettError** [comment]
Can't transfer as MutatorMath and FontMath do not have the same owners.

**Comment by frankrolf** [comment]
Filed in FontMath, closing this one.
Thanks!
