### ISSUE TITLE
Add stylename and family attributes to source element

### ISSUE THREAD

**Issue by LettError** [LettError/MutatorMath#30]
Some consumers of a .designspace document would like to have stylename and familyname attributes in the source element.

**Comment by behdad** [comment]
That would be great, yes.  Thanks!

**Comment by LettError** [comment]
Do you need any other support for these fields, or it is enough that they can be present in the source? #

**Comment by behdad** [comment]
For my use case it's enough if they are in the source, since I'm reading the XML directly.  Thanks.

**Comment by behdad** [comment]
What's the resolution here?

**Comment by LettError** [comment]
DesignSpaceDocumentWriter.addSource takes [familyName and styleName](https://github.com/LettError/MutatorMath/blob/master/Lib/mutatorMath/ufo/document.py#L112) attributes and adds those to source element. 

[Example from exporttest_basic.designspace](https://github.com/LettError/MutatorMath/blob/master/Lib/mutatorMath/test/ufo/data/exporttest_basic.designspace):
```<source familyname="ExplicitSourceFamilyName" filename="sources/light/LightCondensed.ufo" name="master_1" stylename="ExplicitSourceFamilyName">```

**Comment by behdad** [comment]
I see.  Thanks.  Feel free to close.

@jamesgk can you please use this in glyphsLib?

**Comment by jamesgk** [comment]
One issue: styleName is set to family name: https://github.com/LettError/MutatorMath/blob/master/Lib/mutatorMath/ufo/document.py#L176

**Comment by LettError** [comment]
😔fixed.
