### ISSUE TITLE
Maybe DesignSpaceDocumentReader can execute up to self.readSources()

### ISSUE THREAD

**Issue by LettError** [LettError/MutatorMath#35]
[getSourcePaths](https://github.com/LettError/MutatorMath/blob/master/Lib/mutatorMath/ufo/document.py#L392) needs to interpret a part of the designspace to find the sources. Now I also want to read some other data without proceeding all the way through building the instances. So, would it be acceptable to add
```python
        tree = ET.parse(self.path)        
        self.root = tree.getroot()
        self.readVersion()
        assert self.documentFormatVersion == 3
        self.warpDict = None
        self.readWarp()
        self.readSources()
```
..to the __init__? It gives the DesignSpaceDocumentReader some more data to work with, it does not add that much work to the instantiation but it will reduce duplication.

**Comment by behdad** [comment]
I also needed the same (just loading, no building), so I ended up reimplementing the parts I needed in varLib.

**Comment by miguelsousa** [comment]
@LettError just realized that your proposed change was partially implemented in d3d205af60c58e95149ff100b33649086e68e439
Do you want a PR to move the rest?

**Comment by LettError** [comment]
If you could do that, that would be great!

**Comment by miguelsousa** [comment]
done
