### ISSUE TITLE
Mutation fails if the no. of nodes  of .glif are not matching in all master's 

### ISSUE THREAD

**Issue by mdileep** [LettError/MutatorMath#6]
Say 1st glyf is 
```xml
  <contour>
      <point x="442" y="532" type="line"/>
      <point x="233" y="532" type="line"/>
  </contour>
```
Say 2nd glyf is
```xml
  <contour>
      <point x="442" y="532" type="line"/>
      <point x="233" y="532" type="line"/>
       <point x="216" y="377" type="line"/>
  </contour>
```

Mutation fails in this case as 2nd Glyf has more instructions.

Please let me know if the bug is to be on fontstools.

**Comment by miguelsousa** [comment]
@mdileep That's expected. In order to interpolate, the contours need to be compatible (see [**Making it work** section](http://www.robofab.org/talks/robofab_session5.html)).

**Comment by mdileep** [comment]
Thanks   that helped.
