### ISSUE TITLE
set up email notifications on pushes to fontmake-dev?

### ISSUE THREAD

**Issue by anthrotype** [LettError/MutatorMath#75]
Github allows to send an automatic email notification whenever anyone pushes commits, creates/remove branches, pushes tags, etc:

https://help.github.com/articles/managing-notifications-for-pushes-to-a-repository/#enabling-email-service-notifications-for-pushes-to-your-repository

For fontmake and all its dependencies we've configured a Google Groups mailing list to which we send out Github's email notifications as well as those from Appveyor/Travis:

https://groups.google.com/forum/#!forum/fontmake-dev

FontTools also has its own dev list: https://groups.google.com/forum/#!forum/fonttools-dev

It would be nice if you could set up the mutatorMath's repository to send email notifications on pushes to the `fontmake-dev@googlegroups.com` address, so we get notified when you push to master.

The above mentioned link contains the instructions on how to do that.

**Comment by LettError** [comment]
I will look into it.

**Comment by anthrotype** [comment]
It's working, thanks!
