### ISSUE TITLE
Missing license information of test ufos

### ISSUE THREAD

**Issue by medicalwei** [LettError/MutatorMath#96]
Sorry to be picky here, but the licenses of the directory below:
`MutatorMath/Lib/mutatorMath/test/ufo/data/sources/`
seems to be from Adobe Systems Incorporated, according to their [fontinfo.plist](https://github.com/LettError/MutatorMath/blob/master/Lib/mutatorMath/test/ufo/data/sources/light/LightWide.ufo/fontinfo.plist).

Could you add related license information to these files? I am [packaging this for Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=806503) and I need to be careful about license attributions.

**Comment by anthrotype** [comment]
@medicalwei thanks for working on packaging mutatormath for debian!

> Could you add related license information to these files?

Do you mean, we should include the text of the license for the test fonts, in addition to MutatorMath's own license file?
 
From the family name it appears the test data is derived from "AdobeSans". I actually don't know what the license is for that (and I'm no legal expert).

maybe @LettError or @miguelsousa know?

**Comment by medicalwei** [comment]
If you need to switch fonts, some fonts are providing width and weight variants, like Open Sans or Roboto. (these two are Apache Licensed fonts)

(I guess that's Adobe Sans MM, which is one of the first fonts using Multi Master, and you gave me a good typographic history lesson :D)

**Comment by LettError** [comment]
The Adobe Sans data is not complete and broken is specific ways. It can of course be replaced with something else. But it would have to be a compact subset that can be included with MutatorMath. It should not create a dependency on something like Roboto or Source Sans, which are large projects. Alternatively, Adobe could consider making an opensource version of Adobe Sans.

**Comment by miguelsousa** [comment]
> Alternatively, Adobe could consider making an opensource version of Adobe Sans.

@LettError we have no plans to do that. I understand that Source Sans is too big, but you don't have to use the whole thing.

**Comment by LettError** [comment]
I will replace Adobe Sans with some sort of subset of Source Sans.

**Comment by medicalwei** [comment]
Actually the reason why I suggest Roboto is that it has two axises (but the width axis is quite shallow).
I would be happy with any choices you made as long as the licenses are as permissive as BSD or Apache license.

**Comment by LettError** [comment]
I had a quick look and tried to find the condensed masters. Roboto does not actually have 2 axes. It creates a pseudo-condensed by scaling and interpolating the thin and bold regular masters.
So I spent a day drawing some caps to replace all the data that originated from Adobe Sans. They have a similar range in width and weight. The set is not complete, but it will serve for testing. Is it enough that these ufos are covered by the same license as this package or do they need a separate license?

**Comment by anthrotype** [comment]
Same license should be fine, thanks Erik!

**Comment by medicalwei** [comment]
Same license and copyright statement is simpler to cope with. Thank you
Erik!

**Comment by anthrotype** [comment]
https://github.com/LettError/MutatorMath/releases/tag/2.0.7

@medicalwei I presume that downstream maintainers like Debian build their packages from tagged releases. Just let me know in case you need me to create tags for any of the font-related packages that we maintain.
